{
    "name": "BP Market Hub",
    "summary": "Marketplace licensing, consignment inventory, and vendor settlements by Blackpaw Innovations.",
    "version": "17.0.1.0.0",
    "author": "Blackpaw Innovations",
    "website": "https://blackpaw.africa",
    "license": "LGPL-3",
    "category": "Sales/POS",
    "depends": [
        "base",
        "contacts",
        "stock",
        "point_of_sale",
        "pos_hr",
        "account",
        "event",
        "hr",
        "mail",
    ],
    "data": [
        "data/mwanzo_sequences.xml",
        "security/mwanzo_security.xml",
        "security/ir.model.access.csv",
        "report/mwanzo_stock_intake_report.xml",
        "data/mwanzo_stock_intake_email_template.xml",
        "views/bp_mwanzo_menus.xml",
        "views/mwanzo_market_views.xml",
        "views/mwanzo_stock_intake_views.xml",
        "views/pos_views.xml",
        "views/mwanzo_vendor_settlement_views.xml",
        "views/mwanzo_reporting_views.xml",
        "views/dashboard_action.xml",
        "views/dashboard_templates.xml",
        "views/mwanzo_staff_commission_views.xml",
        "views/res_config_settings_views.xml",
        "data/mwanzo_license_cron.xml",
        "data/mwanzo_stock_intake_cron.xml",
        "data/mwanzo_license_data.xml",
        "data/mwanzo_stock_intake_data.xml",
        "data/mwanzo_theme_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "bp_mwanzo_marketplace/static/src/js/dashboard.js",
            "bp_mwanzo_marketplace/static/src/xml/dashboard.xml",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
